# Generated by Django 5.2.7 on 2025-11-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the model', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ToolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('analysismodels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.analysismodel')),
            ],
        ),
    ]
